/** Every user-visible string lives here (docs/SPEC.md 6.6). Keep wording identical to the spec. */
export const S = {
  app: "MarkPDF",
  tagline: "记录每一节课的课件、录音和笔记。",

  nav: { courses: "课程", recent: "最近", settings: "设置" },

  library: {
    title: "课程",
    searchPlaceholder: "搜索课程",
    newCourse: "新建课程",
    emptyTitle: "还没有课程",
    emptyBody: "新建第一门课程，导入 PDF 后即可在课件内录音。",
    sessionsCount: (n: number) => `${n} 段录音`,
    decksCount: (n: number) => `${n} 份课件`,
    rename: "重命名",
    delete: "删除",
    deleteConfirm: "删除课程会同时删除它的课件和录音。",
    recentEmpty: "还没有最近使用的课件",
    chipTranscribed: "转写完成",
    chipSummarized: "总结完成",
  },

  courseDialog: {
    name: "名称",
    term: "学期",
    termPlaceholder: "例如 2026 秋（可空）",
    color: "颜色",
    create: "创建",
    save: "保存",
    cancel: "取消",
  },

  course: {
    startClass: "开始上课",
    importDeck: "导入课件",
    decks: "课件",
    sessions: "课堂记录",
    pages: (n: number) => `${n} 页`,
    sessionsEmptyTitle: "还没有课堂记录",
    sessionsEmptyBody: "点“开始上课”，选一份课件，就可以开始录音。",
    decksEmpty: "还没有课件，先导入一份 PDF。",
    chooseDeck: "选择课件",
    importNew: "导入新课件…",
    retry: "重试",
    statusImporting: "导入中",
    statusUploading: "等待网络",
    statusConverting: (p: number) => `转换中 ${p}%`,
    statusError: "导入失败",
  },

  openFile: {
    opening: (name: string) => `打开 ${name}`,
    checking: "正在检查文件",
    chooseCourse: "导入到哪个课程？",
    chooseCourseBody: (name: string) => `“${name}”还没有导入过，选一个课程来存放它。`,
    noCourses: "还没有课程，先新建一个。",
    newCourse: "新建课程…",
    busyRecording: "录音进行中，结束这节课后再打开新文件。",
    failed: (name: string, reason: string) => `无法打开“${name}”：${reason}`,
  },

  importFlow: {
    copying: "正在复制文件",
    readingPages: (i: number, n: number) => `正在读取页面 ${i} / ${n}`,
    uploading: "正在上传",
    converting: "正在转换为 PDF",
    downloading: "正在下载",
    failed: (reason: string) => `转换失败：${reason}`,
    duplicate: "这份课件已经导入过",
    pptxNeedsLogin: "PPTX 需要登录后由服务器转换为 PDF。",
    pdfOnly: "当前版本只支持 PDF。PPTX 请先在 PowerPoint 里“另存为 PDF”，再导入。",
    login: "登录",
    cancel: "取消",
  },

  session: {
    recording: "录音中",
    back: "返回",
    leaveTitle: "录音仍在进行",
    leaveBody: "结束录音后再离开。",
    continueRecording: "继续录音",
    endClass: "结束录音",
    endTitle: "结束录音？",
    endBody: "录音和转录会保存在此 PDF 中，之后可随时回放。",
    end: "结束",
    prepareBanner: "翻到老师讲的那一页，点工具栏上的录音键开始录音。",
    prepare: "准备录音",
    paused: "已暂停",
    startRecording: "开始录音",
    pauseRecording: "暂停录音",
    backToClass: "回到录音课件",
    startClassRecord: "为此 PDF 新增录音",
    recordingElsewhereTitle: "另一节课正在录音",
    recordingElsewhereBody: "先回到那节课，或者结束它的录音，再在这里开始。",
    endThatClass: "结束那节课的录音",
    playbackFailed: "无法播放录音",
    printFallback: "系统里没有能打印 PDF 的程序。带标注的 PDF 已放到打开的文件夹里，请用其他阅读器打印。",
    markerDisabled: "开始录音后可以标记",
    important: "重点",
    confused: "没听懂",
    homework: "作业",
    followPages: "跟随翻页",
    rename: "重命名",
    exportMarkdown: "导出 Markdown",
    exportPdf: "导出带标注的 PDF",
    print: "打印",
    deleteSession: "删除会话",
    importNewVersion: "导入新版本课件",
    thumbnails: "缩略图",
    outline: "目录",
    noOutline: "这份 PDF 没有目录",
    copyPageText: "复制这一页的文字",
    pageOf: (i: number, n: number) => `${i} / ${n}`,
    renderFailed: "这一页无法渲染",
    goToPage: "跳到页",
    resetLayout: "重置布局",
    addPanel: "添加面板",
  },

  tools: {
    select: "选择",
    highlight: "高亮",
    draw: "绘制",
    text: "添加文本",
    erase: "擦除",
    zoomIn: "放大",
    zoomOut: "缩小",
    fitWidth: "适应宽度",
    fitPage: "适应页面",
    rotate: "旋转",
    view: "视图",
    single: "单页",
    continuous: "连续",
    search: "搜索",
    export: "导出",
    copy: "复制",
    note: "备注",
    translate: "翻译",
    addToNotes: "加入笔记",
    explain: "解释",
    excerpt: "摘录",
    none: "无",
    border: "边框",
    fill: "填充",
  },

  mindmap: {
    emptyTitle: "还没有导图",
    emptyBody: "选中课件文字或标注，点“加入导图”生成摘录卡片；也可以直接新建节点。",
    start: "新建第一个节点",
    addToMap: "加入导图",
  },

  panels: {
    notes: "笔记",
    mindmap: "导图",
    annotations: "标注",
    outline: "目录",
    search: "搜索",
    translate: "翻译",
    explain: "解释",
    transcript: "转写",
    summary: "总结",
    ask: "问答",
    comingSoon: "即将推出",
  },

  notes: {
    page: (n: number) => `第 ${n} 页`,
    live: "实时",
    source: "源码",
    reading: "阅读",
    saved: "已保存",
    saving: "保存中…",
    unsaved: "未保存",
    saveFailed: "保存失败，点击重试",
    recordedAt: (t: string) => `已记录 ${t}`,
    atTime: "当时的笔记",
    current: "现在的笔记",
    placeholder: (n: number) => `在第 ${n} 页写点什么…  支持 Markdown，公式用 $…$`,
    noSnapshotYet: "这时还没有写笔记",
  },

  settings: {
    title: "设置",
    account: "账户",
    localMode: "本地模式",
    loginToSync: "登录以在多台设备间同步",
    logout: "退出登录",
    transcription: "转写",
    liveAsr: "录音时实时转写",
    language: "语言",
    langAuto: "自动",
    langZh: "中文",
    langEn: "English",
    ai: "AI 服务",
    aiBaseUrl: "接口地址",
    aiKey: "API Key",
    aiModel: "模型名",
    aiTest: "测试连接",
    aiOk: "连接正常",
    aiHint: "翻译、解释和（登录后的）总结都通过这个接口。",
    translateTarget: "翻译目标语言",
    annotations: "标注",
    defaultHighlight: "默认高亮色",
    defaultInk: "默认墨迹",
    textBoxFont: "文本框字号",
    textBoxColor: "文本框文字色",
    textBoxBorder: "文本框边框",
    textBoxFill: "文本框填充",
    readingGroup: "阅读",
    defaultView: "默认视图",
    defaultZoom: "默认缩放",
    storage: "存储",
    usedSpace: "已用空间",
    deleteWav: "上传成功后删除本地原始录音",
    clearThumbs: "清理缩略图缓存",
    thumbsCleared: "已清理缩略图缓存",
    syncUnavailable: "本版本未开放账号与同步，所有数据只保存在本机。",
    sync: "同步",
    syncNow: "立即同步",
    appearance: "外观",
    themeSystem: "跟随系统",
    themeLight: "浅色",
    themeDark: "深色",
    shortcuts: "快捷键",
    about: "关于",
    version: "版本",
  },

  transcript: {
    redo: "重新转写",
    redoNow: "用本机模型转写这段录音",
    redoHint: "用本机转写模型重新识别整段录音，替换现有的设备转写",
    redoConfirm: "开始转写",
    redoBody: "会用本机模型识别整段录音，按当时的翻页记录归到各页。",
    redoBodyReplace: "会替换这节课现有的设备转写（包括已做的纠错和翻译），按当时的翻页记录重新归页。",
    redoing: "正在重新转写…",
    redone: (n: number) => `重新转写完成，共 ${n} 句`,
    redoFailed: (m: string) => `重新转写失败：${m}`,
    noModel: "没有可用的转写模型，先在设置里下载一个。",
  },

  toast: {
    saved: "已保存",
    uploaded: "已上传录音",
    summaryStarted: "开始生成总结",
    exported: (path: string) => `已导出到 ${path}`,
    offline: "网络不可用，稍后会自动同步。",
  },

  errors: {
    mic: "麦克风权限被拒绝  在系统设置里允许访问麦克风后重试。",
    upload: "上传失败，稍后会自动重试。",
    asrModel: "转写模型加载失败，录音会继续但没有实时转写。",
    micInterrupted: "麦克风断开或出错，录音已暂停；恢复设备后点“继续录音”。",
    recording: (m: string) => `录音写入失败，已结束这节课并保留已录部分：${m}`,
    recordingStart: (m: string) => `无法开始录音：${m}`,
    wavMissing: (p: string) => `找不到录音文件：${p}`,
    wavUnplayable: (p: string) => `无法播放录音（文件损坏或格式不支持）：${p}`,
    translate: (m: string) => `翻译失败：${m}`,
    explain: (m: string) => `解释失败：${m}`,
    llmUnreachable: (url: string) => `连接不上 AI 服务（${url}）。请检查 Base URL 是否正确、服务是否已启动，以及网络或代理设置。`,
    generic: (m: string) => `出错了：${m}`,
  },

  common: {
    ok: "好",
    cancel: "取消",
    confirm: "确认",
    delete: "删除",
    close: "关闭",
    loading: "加载中…",
  },
} as const;
